name: sqllite
description: A dart wrapper for kipken/sql.js
version: 1.1.0
author: John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/johnpryan/sqllite-dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  js: ^0.6.0
  resource: ^1.1.0

dev_dependencies:
  browser: ^0.10.0
  test: ^0.12.0
